FROM redis:8.4

# Optional: copy custom redis.conf
# COPY ./redis.conf /usr/local/etc/redis/redis.conf

# Optional: expose config or entrypoint
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
