## Simpan snapshot setiap 60 detik jika ada >= 1000 perubahan
save 60 1000

## Aktifkan Append Only File
appendonly yes
appendfsync everysec

## Direktori penyimpanan data
dir /data

# bind 0.0.0.0
# protected-mode no
# maxmemory 256mb
# maxmemory-policy allkeys-lru