FROM postgres:16
# FROM postgres:18.0

# Optional: copy custom config
# COPY ./config/postgres.conf /etc/postgresql/postgresql.conf

# Optional: init scripts
# COPY ./config/db /docker-entrypoint-initdb.d